spring:
  application:
    name: spring-async-demo
  threads:
    virtual:
      enabled: true
  task:
    execution:
      mode: force
      thread-name-prefix: sasync-
      simple:
        concurrency-limit: 100

server:
  port: 48792

logging:
  level:
    root: info
    web: info
    cn.netbuffer: debug
